name: sandpit
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- numpy=1.19.5
- matplotlib
- jupyter
- ipykernel
- pandas
- openpyxl
- scipy
- pip:
  - chemicals
  - mplstereonet
  - dlisio
  - lasio
  - seaborn